// ==========================================
// 🌐 DICCIONARIO DE IDIOMAS (i18n)
// ==========================================
const i18n = {
    en: {
        // --- DRAG & DROP ---
        "drag_drop_title": "📁 Drop your world file here!",
        "drag_drop_subtitle": "Drop the .mbw file anywhere",

        // --- TOP BAR ---
        "btn_file": "File",
        "tooltip_save_now": "Save Now",
        "lbl_auto_save": "Auto save",
        "btn_multiplayer": "Multiplayer",
        "btn_help": "Help",
        "menu_configuration": "Configuration",
        "menu_join_discord": "Join our community!",
        "menu_about": "About...",
        "tooltip_undo": "Undo (Ctrl+Z)",
        "tooltip_redo": "Redo (Ctrl+Y)",
        "tooltip_news": "Updates & Changelog",
        "btn_news": "News",

        // --- RIBBON TABS ---
        "tab_insert": "Insert",
        "tab_world_settings": "World Settings",
        "tab_create": "Create",
        "tab_view": "View",
        "btn_export": "Export",
        "btn_world_info": "World Info",

        // --- INSERT TAB ---
        "tooltip_paste": "Paste (Ctrl+V)",
        "btn_paste": "Paste",
        "tooltip_cut": "Cut (Ctrl+X)",
        "tooltip_copy": "Copy (Ctrl+C)",
        "lbl_clipboard": "Clipboard",
        "lbl_size": "Size",
        "lbl_rounded": "Rounded",
        "tooltip_spray": "Toggle Spray Mode",
        "btn_spray": "Spray",
        "lbl_brush_settings": "Brush Settings",
        "tooltip_inventory": "Open Inventory (E)",
        "lbl_inventory": "Inventory (E)",
        "tooltip_save_struct": "Select an area first",
        "btn_save_structure_multiline": "Save<br>Structure",
        "lbl_empty": "Empty",
        "tooltip_structures": "Open Library / See All",
        "lbl_structures_tab": "Structures (R)",
        "tooltip_mobs": "Open Mob Browser",
        "lbl_mobs_tab": "Mobs (M)",

        // --- WORLD SETTINGS TAB ---
        "lbl_gamemode": "Gamemode:",
        "gm_survival": "Survival",
        "gm_creative": "Creative",
        "gm_adventure": "Adventure",
        "gm_spectator": "Spectator",
        "lbl_difficulty": "Difficulty:",
        "diff_peaceful": "Peaceful",
        "diff_easy": "Easy",
        "diff_normal": "Normal",
        "diff_hard": "Hard",
        "lbl_cheats": "Cheats",
        "lbl_hardcore": "Hardcore",
        "lbl_day": "Day:",
        "tooltip_days_passed": "Days passed (Read Only)",
        "lbl_time": "Time:",
        "lbl_live_time": "Live Time",
        "lbl_weather": "Weather",
        "weather_clear": "Clear",
        "weather_rain": "Rain",
        "weather_thunder": "Thunder",
        "lbl_world_settings": "World Settings",
        "btn_manage_achievements": "Manage<br>Achievs.",
        "lbl_achievements": "Achievements",
        "lbl_keep_inv": "Keep<br>Inv.",
        "lbl_daylight_cycle": "Daylight<br>Cycle",
        "lbl_mob_griefing": "Mob<br>Griefing",
        "lbl_mob_loot": "Mob<br>Loot",
        "lbl_fire_tick": "Fire<br>Tick",
        "lbl_gamerules": "Game Rules",
        "lbl_health": "Health",
        "lbl_hunger": "Hunger",
        "lbl_xp": "XP",
        "lbl_player": "Player",

        // --- CREATE TAB ---
        "btn_create_chest": "Create<br>Loot Chest",
        "lbl_chests": "Chests",
        "btn_create_item": "Create<br>Item",
        "lbl_custom_items": "Custom Items",

        // --- VIEW TAB ---
        "lbl_show_grid": "Show Grid",
        "lbl_grid": "Grid",
        "btn_change_dim": "Change<br>Dimension",
        "lbl_dimensions": "Dimensions",
        "lbl_weather_anim": "Weather<br>Animation",

        // --- TOOLBAR ---
        "tooltip_tool_move": "Move Tool",
        "tooltip_tool_pencil": "Pencil",
        "tooltip_tool_eraser": "Eraser",
        "tooltip_tool_bucket": "Bucket",
        "tooltip_tool_select": "Select",
        "tooltip_tool_magic": "Magic Wand",
        "tooltip_tool_lasso": "Free form",
        "tooltip_tool_eyedropper": "Eyedropper",
        "tooltip_screenshot": "Screenshot",

        // --- SIDEBAR WORLD INFO ---
        "side_info_title": "World Info",
        "side_info_name": "World Name:",
        "side_info_author": "Author:",
        "side_info_version": "Version:",
        "side_info_seed": "Seed:",
        "side_info_cheats": "Cheats Enabled:",
        "side_info_dragon": "Defeated Enderdragon:",
        "side_info_size": "File Size: ",

        // --- MODAL: SETTINGS ---
        "config_title": "Configuration",
        "config_language": "Language",
        "config_theme": "Theme",
        "config_autosave": "Auto-Save Interval",
        "config_off": "Off (Disabled)",
        "config_1m": "Every 1 minute",
        "config_5m": "Every 5 minutes",
        "config_10m": "Every 10 minutes",
        "config_volume": "Master Volume",

        // --- MODAL: INVENTORY ---
        "modal_inventory": "Inventory",
        "pl_search": "Search...",
        "chest_content_title": "Loot Chest Content",
        "pl_chest_name": "Chest Name...",
        "btn_save_chest": "Save Chest",
        "item_creator_title": "Custom Item Creator",
        "btn_save_item": " Save Item",
        "msg_select_first": "Select an item",
        "lbl_enchantments": "Enchantments",

        // --- MODAL: STRUCTURES ---
        "struct_browser_title": "Structures Browser",
        "tab_saved": "Saved",
        "tab_vanilla": "Vanilla",
        "tab_community": "Community",
        "tooltip_import_json": "Import JSON",
        "btn_import_mini": " Import",
        "tooltip_export_json": "Export JSON",
        "btn_export_mini": " Export",
        "tooltip_delete_all": "Delete All Saved",
        "btn_reset_mini": " Reset",
        "sub_all": "All",
        "sub_structures": "Structures",
        "sub_chests": "Chests",
        "sub_houses": "Houses",
        "sub_pixel_art": "Pixel Art",
        "sub_other": "Other",
        "btn_gen_chest": "Generate Chest",
        "lbl_author": "Author:",
        "lbl_category": "Category:",
        "btn_load_struct": "Load Structure",
        "tooltip_edit_info": "Edit Info",
        "btn_edit": "Edit",
        "tooltip_delete": "Delete",
        "btn_delete": "Delete",

        // --- MODAL: MOBS ---
        "mob_browser_title": "Mob Browser",
        "tab_animals": "Animals",
        "tab_overworld": "Overworld",
        "tab_nether": "Nether",
        "tab_end": "End",
        "lbl_health_hp": "Health: 20 HP",
        "btn_spawn_mob": "Spawn Mob",

        // --- MODAL: SAVE STRUCTURE ---
        "modal_save_struct_title": "Save New Structure",
        "lbl_title": "Title",
        "pl_text": "Text",
        "pl_username": "Username",
        "lbl_category_hidden": "Category",
        "lbl_tag": "Tag",
        "sub_structure": "Structure",
        "sub_house": "House",
        "sub_vehicle": "Vehicle",
        "btn_cancel": "Cancel",
        "btn_save": "Save",

        // --- MODAL: ACHIEVEMENTS ---
        "achiev_title": "Achievements",
        "btn_unlock_all": "Unlock All",
        "btn_reset_all": "Reset All",
        "ach_breed": "Breed two animals",
        "ach_brew": "Brew a potion",
        "ach_crafting": "Craft a crafting table",
        "ach_stone_pick": "Craft a stone pickaxe",
        "ach_wood_pick": "Craft a wooden pickaxe",
        "ach_iron_pick": "Craft an iron pickaxe",
        "ach_flaming_chicken": "Defeat a flaming chicken",
        "ach_eat": "Eat some food",
        "ach_enchant": "Enchant an item",
        "ach_bow": "Fire a bow",
        "ach_fish": "Fish a fish",
        "ach_farm": "Grow a farm",
        "ach_tree": "Grow a tree",
        "ach_cake": "Make a cake",
        "ach_furnace": "Make a furnace",
        "ach_iron_ingot": "Make an iron ingot",
        "ach_portal_stone": "Make portal stone",
        "ach_torches": "Make some torches",
        "ach_mine_wood": "Mine a block of wood",
        "ach_mine_diamond": "Mine diamonds",
        "ach_mine_gold": "Mine gold",
        "ach_mine_obsidian": "Mine obsidian",
        "ach_door_wiring": "Open a door with wiring",
        "ach_open_inv": "Open the inventory",
        "ach_place_block": "Place a block",
        "ach_slay_blaze": "Slay a blaze",
        "ach_slay_cow": "Slay a cow",
        "ach_slay_creeper": "Slay a creeper",
        "ach_slay_ghast": "Slay a ghast by its fireball",
        "ach_slay_magma": "Slay a magma cube",
        "ach_slay_nethereye": "Slay a nethereye",
        "ach_slay_pig": "Slay a pig",
        "ach_slay_sheep": "Slay a sheep",
        "ach_slay_skeleton": "Slay a skeleton",
        "ach_slay_slime": "Slay a slime",
        "ach_slay_spider": "Slay a spider",
        "ach_slay_zombie": "Slay a zombie",
        "ach_slay_zpigman": "Slay a zombie pigman",
        "ach_slay_enderman": "Slay an enderman",
        "ach_slay_dragon": "Slay the ender dragon",
        "ach_tame_dog": "Tame a dog",
        "ach_tp_pearl": "Teleport with enderpearl",
        "ach_travel_nether": "Travel to the nether",
        "ach_unlock_end": "Unlock the ender portal",
        "ach_use_bed": "Use a bed",
        "ach_use_anvil": "Use an anvil",

        // --- MODAL: DIMENSIONS ---
        "dim_title": "Select Dimension",

        // --- MODAL: EDIT INFO ---
        "edit_info_title": "Edit Structure Info",
        "btn_update": "Update",

        // --- MODAL: CONFIRM ---
        "confirm_title": "Confirm Action",
        "confirm_msg": "Are you sure?",
        "btn_yes": "Yes",
        "btn_no": "No",

        // --- MODAL: NEWS ---
        "news_title": "📰 Updates",
        "btn_back": "Back",

        // --- MODAL: LIGHTBOX ---
        "tooltip_close": "Close",

        // --- LOADING ---
        "loading_world": "Loading World...",

        // --- CHAT ---
        "pl_chat": "Press Enter to chat...",

        // --- STATUS BAR ---
        "tooltip_fps": "Frames Per Second",
        "status_ready": "Ready",
        "tooltip_zoom_out": "Zoom Out",
        "tooltip_zoom_in": "Zoom In",
        "tooltip_zoom_reset": "Click to Reset",
        "tooltip_fullscreen": "Fullscreen",

        // --- PROFILE ---
        "profile_title": "My Profile",
        "lbl_username": "Username:",

        // --- ABOUT ---
        "about_desc": "A Mine Blocks web-tool to design, edit, and share your favorite worlds directly from your browser.",
        "about_last_update": "Last Update:",

        // --- UI HANDLER JS ---
        "cat_all": "All Items",
        "cat_custom": "Custom",
        "cat_blocks": "Blocks",
        "cat_decoration": "Decoration",
        "cat_transportation": "Transportation",
        "cat_tools": "Tools",
        "cat_food": "Food and Crops",
        "cat_armor": "Armor",
        "cat_potions": "Potions",
        "cat_enchantedbooks": "Enchanted Books",

        "tooltip_open_inv": "Click to open Inventory",
        "lbl_creative_inv": "Creative Inventory",
        "pl_search_item": "Search item... (e.g. Diamond)",
        "lbl_none": "None",
        "tooltip_spawn": "Spawn",
        "msg_no_bases": "No bases found.",
        "msg_no_custom_mobs": "No custom mobs yet.<br>Go to Create > Custom Mob!",
        "lbl_health_hp_prefix": "Health: ",
        "msg_system": "System",
        "msg_spawn_custom": "⚡ You spawned your creation: ",
        "msg_spawn_saved": "⚡ Created and saved: ",
        "err_template_not_found": "Error: Template not found for",
        "lbl_mutant": "Mutant",
        "lbl_enchanted_book": "Enchanted Book",
        "lbl_potion_effect": "Potion Effect",
        "lbl_custom_chest": "Custom Chest",
        "msg_tp": "WHOOSH! Teleported to",
		
		// --- FILE MENU (BACKSTAGE) ---
        "menu_back": "Back",
        "menu_my_worlds": "My Worlds",
        "menu_templates": "Templates",
        "menu_multiplayer": "Multiplayer",
        "menu_load_world": "Load World",
        "menu_export": "Export",
        "tooltip_change_pfp": "Click to change picture",
        "mp_public_servers": "Public Servers",
        "mp_searching_worlds": "Searching for worlds...",
        "mp_join_or_create": "Join by ID or Create your own:",
        "mp_create_server": "Create Server",
        "mp_paste_id": "Paste ID here...",
        "mp_connect": "Connect",
        "mp_players_limit": "Players Limit:",
        "mp_access": "Access: ",
        "mp_public": "Public",
        "mp_next": "Next",
        "mp_cancel": "Cancel",
        "mp_select_map": "Select Map:",
        "mp_generate_start": "Generate ID & Start",
        "mp_room_id": "Your Room ID (Share this):",
        "mp_click_copy": "Click to copy!",
        "mp_id_placeholder": "ID will appear here...",
        "mp_copied": "Copied to clipboard!",
        "mp_close_server": "Close Server & Back",
        "mp_status_not_connected": "Status: Not Connected",
        "mp_online": "Online",
        "mp_loading_players": "Loading players...",
        "mp_chats": "Chats",
        "mp_select_chat": "Select a chat to start",
        "mp_name_placeholder": "Name",
        "mp_send_message": "Send a message...",
        "mp_inbox": "Inbox",
        "fs_no_saved_worlds": "No saved worlds yet",
        "fs_start_template": "Start from a Template",
        "tooltip_delete_world": "Delete World",
		"config_startup": "Startup Screen",
        "startup_editor": "Normal Editor",
        "startup_filemenu": "File Menu",
		// --- ADDON: PIXEL ART ---
        "pixelart_title": "Pixel Art Auto-Builder",
        "pixelart_desc": "Upload an image and the editor will build it in the world using wool and clay blocks.",
        "pixelart_max_width": "Max Size (Width in Blocks):",
        "pixelart_warning": "Very large images may cause lag.",
        "btn_pixelart_upload": "Upload Image & Build",
		"config_tab_theme": "🎨 Theme",
        "config_tab_autosave": "💾 Auto-save",
        "config_tab_language": "🌍 Language",
        "config_tab_startup": "🚀 Startup",
        "config_tab_volume": "🔊 Volume",
        "config_tab_controls": "⌨️ Controls",
        "config_theme_select": "Select your preferred theme:",
        "theme_dark": "⚫ Dark (Default)",
        "theme_white": "⚪ White",
        "theme_pastel": "🌸 Pastel",
        "theme_pastel2": "🌸 Pastel 2 (Cool)",
        "theme_darkblue": "🔵 Dark Blue",
        "theme_winxp": "🪟 Windows XP",
        "config_autosave_label": "Auto-Save Interval:",
        "config_language_label": "Select Language:",
        "config_startup_label": "Choose what to see when opening the app:",
        "config_volume_desc": "Adjust general audio level",
        "btn_reset_keybinds": "Reset Defaults",
        "controls_instructions": "Click a button and press a new key to change the shortcut.",
		"addons_tab_btn": "➕ Addons",
        "addon_spawnskin_title": "Spawnskins Preview",
        "addon_spawnskin_desc": "Upload skin spreadsheets to see the spawnskin preview in the world.",
        "addon_pixelart_title": "[Demo] Pixel Art Auto-Builder",
        "addon_pixelart_desc": "Convert any image into a large pixel art.",
        "btn_open_addon": "Open",
        "btn_more_addons": "➕ More Add-ins",
		"spawnskin_modal_title": "Spawnskins Preview Generator",
        "spawnskin_modal_desc": "To see the spawnskins in the editor, you need to use this tool.",
        "spawnskin_step1": "1. Open 'Spawnskins Preview Generator'",
        "btn_open_generator": "Open Tool",
        "spawnskin_step2": "2. Load the skin list here:",
        "btn_import_skins": "Import skins",
        "lbl_imported_skins": "Imported Spawnskins",
		"news_title": "📰 Updates",
    "btn_back": "Back",
    "news_v23_title": "v2.3 - Multiplayer Update",
    "news_v23_date": "April 25, 2026",
    "news_v23_desc": "Create a map with friends, chat with them, and more!",
    "news_v22_title": "v2.2 - Chests Update",
    "news_v22_date": "March 23, 2026",
    "news_v22_desc": "Huge update including new structures, magic wand, custom items, tabs system, and much more!",
    "news_v21_title": "v2.1 - Structures Update",
    "news_v21_date": "February 23, 2026",
    "news_v21_desc": "Structures library, improved tools, new UI, and bug fixes.",
    "news_v20_title": "v2.0",
    "news_v20_date": "January 16, 2026",
    "news_v20_desc": "New UI, Copy-Paste, Zoom, and more!",
    },
    
	
	
	
	
	
	
	
    es: {
        // --- DRAG & DROP ---
        "drag_drop_title": "📁 ¡Suelta tu mundo aquí!",
        "drag_drop_subtitle": "Arrastra el archivo .mbw en cualquier parte",

        // --- TOP BAR ---
        "btn_file": "Archivo",
        "tooltip_save_now": "Guardar Ahora",
        "lbl_auto_save": "Autoguardado",
        "btn_multiplayer": "Multijugador",
        "btn_help": "Ayuda",
        "menu_configuration": "Configuración",
        "menu_join_discord": "¡Únete a la comunidad!",
        "menu_about": "Acerca de...",
        "tooltip_undo": "Deshacer (Ctrl+Z)",
        "tooltip_redo": "Rehacer (Ctrl+Y)",
        "tooltip_news": "Novedades y Cambios",
        "btn_news": "Noticias",

        // --- RIBBON TABS ---
        "tab_insert": "Insertar",
        "tab_world_settings": "Mundo",
        "tab_create": "Crear",
        "tab_view": "Vista",
        "btn_export": "Exportar",
        "btn_world_info": "Info. Mundo",

        // --- INSERT TAB ---
        "tooltip_paste": "Pegar (Ctrl+V)",
        "btn_paste": "Pegar",
        "tooltip_cut": "Cortar (Ctrl+X)",
        "tooltip_copy": "Copiar (Ctrl+C)",
        "lbl_clipboard": "Portapapeles",
        "lbl_size": "Tamaño",
        "lbl_rounded": "Círculo",
        "tooltip_spray": "Activar Spray",
        "btn_spray": "Spray",
        "lbl_brush_settings": "Pinceles",
        "tooltip_inventory": "Abrir Inventario (E)",
        "lbl_inventory": "Inventario (E)",
        "tooltip_save_struct": "Selecciona un área primero",
        "btn_save_structure_multiline": "Guardar<br>Estructura",
        "lbl_empty": "Vacío",
        "tooltip_structures": "Abrir Librería / Ver Todas",
        "lbl_structures_tab": "Estructuras (R)",
        "tooltip_mobs": "Abrir Mobs",
        "lbl_mobs_tab": "Mobs (M)",

        // --- WORLD SETTINGS TAB ---
        "lbl_gamemode": "Modo:",
        "gm_survival": "Supervivencia",
        "gm_creative": "Creativo",
        "gm_adventure": "Aventura",
        "gm_spectator": "Espectador",
        "lbl_difficulty": "Dificultad:",
        "diff_peaceful": "Pacífico",
        "diff_easy": "Fácil",
        "diff_normal": "Normal",
        "diff_hard": "Difícil",
        "lbl_cheats": "Trucos",
        "lbl_hardcore": "Extremo",
        "lbl_day": "Día:",
        "tooltip_days_passed": "Días transcurridos (Solo lectura)",
        "lbl_time": "Hora:",
        "lbl_live_time": "Tiempo Real",
        "lbl_weather": "Clima",
        "weather_clear": "Despejado",
        "weather_rain": "Lluvia",
        "weather_thunder": "Tormenta",
        "lbl_world_settings": "Opciones de Mundo",
        "btn_manage_achievements": "Gestionar<br>Logros",
        "lbl_achievements": "Logros",
        "lbl_keep_inv": "Cons.<br>Inv.",
        "lbl_daylight_cycle": "Ciclo<br>Día",
        "lbl_mob_griefing": "Daño<br>Mobs",
        "lbl_mob_loot": "Botín<br>Mobs",
        "lbl_fire_tick": "Propa.<br>Fuego",
        "lbl_gamerules": "Reglas de Juego",
        "lbl_health": "Vida",
        "lbl_hunger": "Hambre",
        "lbl_xp": "Experiencia",
        "lbl_player": "Jugador",

        // --- CREATE TAB ---
        "btn_create_chest": "Crear<br>Cofre",
        "lbl_chests": "Cofres",
        "btn_create_item": "Crear<br>Ítem",
        "lbl_custom_items": "Ítems",

        // --- VIEW TAB ---
        "lbl_show_grid": "Ver Cuadrícula",
        "lbl_grid": "Cuadrícula",
        "btn_change_dim": "Cambiar<br>Dimensión",
        "lbl_dimensions": "Dimensiones",
        "lbl_weather_anim": "Anim.<br>de Clima",

        // --- TOOLBAR ---
        "tooltip_tool_move": "Mover",
        "tooltip_tool_pencil": "Lápiz",
        "tooltip_tool_eraser": "Borrador",
        "tooltip_tool_bucket": "Cubeta",
        "tooltip_tool_select": "Seleccionar",
        "tooltip_tool_magic": "Varita Mágica",
        "tooltip_tool_lasso": "Lazo",
        "tooltip_tool_eyedropper": "Gotero",
        "tooltip_screenshot": "Captura de Pantalla",

        // --- SIDEBAR WORLD INFO ---
        "side_info_title": "Información",
        "side_info_name": "Nombre:",
        "side_info_author": "Creador:",
        "side_info_version": "Versión:",
        "side_info_seed": "Semilla:",
        "side_info_cheats": "Trucos Activados:",
        "side_info_dragon": "Enderdragon Vencido:",
        "side_info_size": "Tamaño: ",

        // --- MODAL: SETTINGS ---
        "config_title": "Configuración",
        "config_language": "Idioma",
        "config_theme": "Tema / Apariencia",
        "config_autosave": "Intervalo de Autoguardado",
        "config_off": "Desactivado",
        "config_1m": "Cada 1 minuto",
        "config_5m": "Cada 5 minutos",
        "config_10m": "Cada 10 minutos",
        "config_volume": "Volumen Principal",

        // --- MODAL: INVENTORY ---
        "modal_inventory": "Inventario",
        "pl_search": "Buscar...",
        "chest_content_title": "Contenido del Cofre",
        "pl_chest_name": "Nombre del cofre...",
        "btn_save_chest": "Guardar Cofre",
        "item_creator_title": "Creador de Ítems",
        "btn_save_item": " Guardar Ítem",
        "msg_select_first": "Selecciona un ítem",
        "lbl_enchantments": "Encantamientos",

        // --- MODAL: STRUCTURES ---
        "struct_browser_title": "Librería de Estructuras",
        "tab_saved": "Guardadas",
        "tab_vanilla": "Vanilla",
        "tab_community": "Comunidad",
        "tooltip_import_json": "Importar Archivo JSON",
        "btn_import_mini": " Importar",
        "tooltip_export_json": "Exportar Archivo JSON",
        "btn_export_mini": " Exportar",
        "tooltip_delete_all": "Borrar todas las guardadas",
        "btn_reset_mini": "️Reiniciar",
        "sub_all": "Todo",
        "sub_structures": "Estructuras",
        "sub_chests": "Cofres",
        "sub_houses": "Casas",
        "sub_pixel_art": "Pixel Art",
        "sub_other": "Otros",
        "btn_gen_chest": "Generar Cofre",
        "lbl_author": "Creador:",
        "lbl_category": "Categoría:",
        "btn_load_struct": "Cargar Estructura",
        "tooltip_edit_info": "Editar Info",
        "btn_edit": "Editar",
        "tooltip_delete": "Eliminar",
        "btn_delete": "Eliminar",

        // --- MODAL: MOBS ---
        "mob_browser_title": "Librería de Mobs",
        "tab_animals": "Animales",
        "tab_overworld": "Superficie",
        "tab_nether": "Nether",
        "tab_end": "End",
        "lbl_health_hp": "Vida: 20 HP",
        "btn_spawn_mob": "Spawnear",

        // --- MODAL: SAVE STRUCTURE ---
        "modal_save_struct_title": "Guardar Nueva Estructura",
        "lbl_title": "Nombre",
        "pl_text": "Texto",
        "pl_username": "Usuario",
        "lbl_category_hidden": "Categoría",
        "lbl_tag": "Etiqueta",
        "sub_structure": "Estructura",
        "sub_house": "Casa",
        "sub_vehicle": "Vehículo",
        "btn_cancel": "Cancelar",
        "btn_save": "Guardar",

        // --- MODAL: ACHIEVEMENTS ---
        "achiev_title": "Logros",
        "btn_unlock_all": "Desbloquear",
        "btn_reset_all": "Reiniciar",
        "ach_breed": "Reproducir dos animales",
        "ach_brew": "Hacer una poción",
        "ach_crafting": "Hacer una mesa de crafteo",
        "ach_stone_pick": "Hacer un pico de piedra",
        "ach_wood_pick": "Hacer un pico de madera",
        "ach_iron_pick": "Hacer un pico de hierro",
        "ach_flaming_chicken": "Derrotar al Pollo en Llamas",
        "ach_eat": "Comer algo",
        "ach_enchant": "Encantar un ítem",
        "ach_bow": "Disparar un arco",
        "ach_fish": "Pescar un pez",
        "ach_farm": "Cultivar algo",
        "ach_tree": "Plantar un árbol",
        "ach_cake": "Hacer un pastel",
        "ach_furnace": "Hacer un horno",
        "ach_iron_ingot": "Fundir un lingote de hierro",
        "ach_portal_stone": "Crear Piedra de Portal",
        "ach_torches": "Crear antorchas",
        "ach_mine_wood": "Minar madera",
        "ach_mine_diamond": "Minar diamantes",
        "ach_mine_gold": "Minar oro",
        "ach_mine_obsidian": "Minar obsidiana",
        "ach_door_wiring": "Abrir una puerta con cables",
        "ach_open_inv": "Abrir el inventario",
        "ach_place_block": "Colocar un bloque",
        "ach_slay_blaze": "Matar a un Blaze",
        "ach_slay_cow": "Matar a una Vaca",
        "ach_slay_creeper": "Matar a un Creeper",
        "ach_slay_ghast": "Matar a un Ghast con su fuego",
        "ach_slay_magma": "Matar a un Cubo de Magma",
        "ach_slay_nethereye": "Matar a un Nethereye",
        "ach_slay_pig": "Matar a un Cerdo",
        "ach_slay_sheep": "Matar a una Oveja",
        "ach_slay_skeleton": "Matar a un Esqueleto",
        "ach_slay_slime": "Matar a un Slime",
        "ach_slay_spider": "Matar a una Araña",
        "ach_slay_zombie": "Matar a un Zombie",
        "ach_slay_zpigman": "Matar a un Hombrecerdo",
        "ach_slay_enderman": "Matar a un Enderman",
        "ach_slay_dragon": "Matar al Dragón del End",
        "ach_tame_dog": "Domesticar a un perro",
        "ach_tp_pearl": "Teletransportarse con perla",
        "ach_travel_nether": "Viajar al Nether",
        "ach_unlock_end": "Desbloquear el Portal al Fin",
        "ach_use_bed": "Dormir en una cama",
        "ach_use_anvil": "Usar un yunque",

        // --- MODAL: DIMENSIONS ---
        "dim_title": "Seleccionar Dimensión",

        // --- MODAL: EDIT INFO ---
        "edit_info_title": "Editar Información",
        "btn_update": "Actualizar",

        // --- MODAL: CONFIRM ---
        "confirm_title": "Confirmar Acción",
        "confirm_msg": "¿Estás seguro?",
        "btn_yes": "Sí",
        "btn_no": "No",

        // --- MODAL: NEWS ---
        "news_title": "📰 Novedades",
        "btn_back": "Volver",

        // --- MODAL: LIGHTBOX ---
        "tooltip_close": "Cerrar",

        // --- LOADING ---
        "loading_world": "Cargando Mundo...",

        // --- CHAT ---
        "pl_chat": "Presiona Enter para hablar...",

        // --- STATUS BAR ---
        "tooltip_fps": "Fotogramas Por Segundo",
        "status_ready": "Listo",
        "tooltip_zoom_out": "Alejar",
        "tooltip_zoom_in": "Acercar",
        "tooltip_zoom_reset": "Restablecer",
        "tooltip_fullscreen": "Pantalla Completa",

        // --- PROFILE ---
        "profile_title": "Mi Perfil",
        "lbl_username": "Nombre de Usuario:",

        // --- ABOUT ---
        "about_desc": "Una herramienta web para Mine Blocks. Diseña, edita y comparte tus mundos favoritos directamente desde tu navegador.",
        "about_last_update": "Última Actualización:",

        // --- UI HANDLER JS ---
        "cat_all": "Todos",
        "cat_custom": "Personalizado",
        "cat_blocks": "Bloques",
        "cat_decoration": "Decoración",
        "cat_transportation": "Transporte",
        "cat_tools": "Herramientas",
        "cat_food": "Comida y Cultivos",
        "cat_armor": "Armaduras",
        "cat_potions": "Pociones",
        "cat_enchantedbooks": "Libros Encantados",

        "tooltip_open_inv": "Clic para abrir el Inventario",
        "lbl_creative_inv": "Inventario Creativo",
        "pl_search_item": "Buscar ítem... (ej. Diamante)",
        "lbl_none": "Ninguno",
        "tooltip_spawn": "Aparecer",
        "msg_no_bases": "No se encontraron bases.",
        "msg_no_custom_mobs": "Aún no hay mobs personalizados.<br>¡Ve a Crear > Mob Custom!",
        "lbl_health_hp_prefix": "Vida: ",
        "msg_system": "Sistema",
        "msg_spawn_custom": "⚡ Has spawneado tu creación: ",
        "msg_spawn_saved": "⚡ Creado y guardado: ",
        "err_template_not_found": "Error: No encontré la plantilla de ",
        "lbl_mutant": "Mutante ",
        "lbl_enchanted_book": "Libro Encantado",
        "lbl_potion_effect": "Efecto de Poción",
        "lbl_custom_chest": "Cofre Personalizado",
        "msg_tp": "¡FIIUUM! Teletransportado a",
		
		// --- FILE MENU (BACKSTAGE) ---
        "menu_back": "Volver",
        "menu_my_worlds": "Mis Mundos",
        "menu_templates": "Plantillas",
        "menu_multiplayer": "Multijugador",
        "menu_load_world": "Cargar Mundo",
        "menu_export": "Exportar",
        "tooltip_change_pfp": "Clic para cambiar foto",
        "mp_public_servers": "Servidores Públicos",
        "mp_searching_worlds": "Buscando mundos...",
        "mp_join_or_create": "Únete por ID o Crea el tuyo:",
        "mp_create_server": "Crear Servidor",
        "mp_paste_id": "Pega la ID aquí...",
        "mp_connect": "Conectar",
        "mp_players_limit": "Límite de Jugadores:",
        "mp_access": "Acceso: ",
        "mp_public": "Público",
        "mp_next": "Siguiente",
        "mp_cancel": "Cancelar",
        "mp_select_map": "Seleccionar Mapa:",
        "mp_generate_start": "Generar ID e Iniciar",
        "mp_room_id": "Tu ID de Sala (Compártelo):",
        "mp_click_copy": "¡Clic para copiar!",
        "mp_id_placeholder": "La ID aparecerá aquí...",
        "mp_copied": "¡Copiado al portapapeles!",
        "mp_close_server": "Cerrar Servidor y Volver",
        "mp_status_not_connected": "Estado: No Conectado",
        "mp_online": "En Línea",
        "mp_loading_players": "Cargando jugadores...",
        "mp_chats": "Chats",
        "mp_select_chat": "Selecciona un chat para iniciar",
        "mp_name_placeholder": "Nombre",
        "mp_send_message": "Enviar un mensaje...",
        "mp_inbox": "Bandeja",
        "fs_no_saved_worlds": "Aún no hay mundos guardados",
        "fs_start_template": "Comenzar desde una Plantilla",
        "tooltip_delete_world": "Eliminar Mundo",
		"config_startup": "Pantalla de inicio",
        "startup_editor": "Editor Normal",
        "startup_filemenu": "Menú de Archivos",
		// --- ADDON: PIXEL ART ---
        "pixelart_title": "Auto-Constructor de Pixel Art",
        "pixelart_desc": "Sube una imagen y el editor la construirá en el mundo usando bloques de lana y arcilla.",
        "pixelart_max_width": "Tamaño Máximo (Ancho en Bloques):",
        "pixelart_warning": "Imágenes muy grandes pueden dar lag.",
        "btn_pixelart_upload": "Cargar Imagen y Construir",
		"config_tab_theme": "🎨 Tema",
        "config_tab_autosave": "💾 Auto-guardado",
        "config_tab_language": "🌍 Idioma",
        "config_tab_startup": "🚀 Inicio",
        "config_tab_volume": "🔊 Volumen",
        "config_tab_controls": "⌨️ Controles",
        "config_theme_select": "Selecciona tu tema preferido:",
        "theme_dark": "⚫ Oscuro (Predeterminado)",
        "theme_white": "⚪ Blanco",
        "theme_pastel": "🌸 Pastel",
        "theme_pastel2": "🌸 Pastel 2 (Cool)",
        "theme_darkblue": "🔵 Azul Oscuro",
        "theme_winxp": "🪟 Windows XP",
        "config_autosave_label": "Intervalo de auto-guardado:",
        "config_language_label": "Seleccionar idioma:",
        "config_startup_label": "Elige qué ver al abrir la aplicación:",
        "config_volume_desc": "Ajustar nivel de audio general",
        "btn_reset_keybinds": "Restablecer",
        "controls_instructions": "Haz clic en un botón y presiona una tecla nueva para cambiar el atajo.",
		"addons_tab_btn": "➕ Addons",
        "addon_spawnskin_title": "Previsualización de Spawnskins",
        "addon_spawnskin_desc": "Sube hojas de skins para ver la previsualización de spawnskins en el mundo.",
        "addon_pixelart_title": "[Demo] Auto-Constructor de Pixel Art",
        "addon_pixelart_desc": "Convierte cualquier imagen en un pixel art gigante.",
        "btn_open_addon": "Abrir",
        "btn_more_addons": "➕ Más Add-ins",
		"spawnskin_modal_title": "Generador de Previsualización de Spawnskins",
        "spawnskin_modal_desc": "Para ver las spawnskins en el editor, necesitas usar esta herramienta.",
        "spawnskin_step1": "1. Abre el 'Generador de Previsualización de Spawnskins'",
        "btn_open_generator": "Abrir Herramienta",
        "spawnskin_step2": "2. Carga la lista de skins aquí:",
        "btn_import_skins": "Importar skins",
        "lbl_imported_skins": "Spawnskins Importadas",
		"news_title": "📰 Novedades",
    "btn_back": "Volver",
    "news_v23_title": "v2.3 - Actualización Multijugador",
    "news_v23_date": "25 de Abril, 2026",
    "news_v23_desc": "¡Crea un mapa con amigos, chatea con ellos y más!",
    "news_v22_title": "v2.2 - Actualización de Cofres",
    "news_v22_date": "23 de Marzo, 2026",
    "news_v22_desc": "¡Gran actualización que incluye nuevas estructuras, varita mágica, objetos personalizados, sistema de pestañas y mucho más!",
    "news_v21_title": "v2.1 - Actualización de Estructuras",
    "news_v21_date": "23 de Febrero, 2026",
    "news_v21_desc": "Librería de estructuras, herramientas mejoradas, nueva interfaz y corrección de errores.",
    "news_v20_title": "v2.0",
    "news_v20_date": "16 de Enero, 2026",
    "news_v20_desc": "¡Nueva interfaz, Copiar-Pegar, Zoom y más!",
    },
	
	
	
	
	
	
	
	
	pt: {
        // --- DRAG & DROP ---
        "drag_drop_title": "📁 Solte o arquivo do seu mundo aqui!",
        "drag_drop_subtitle": "Solte o arquivo .mbw em qualquer lugar",

        // --- TOP BAR ---
        "btn_file": "Arquivo",
        "tooltip_save_now": "Salvar Agora",
        "lbl_auto_save": "Salvamento automático",
        "btn_multiplayer": "Multijogador",
        "btn_help": "Ajuda",
        "menu_configuration": "Configuração",
        "menu_join_discord": "Junte-se à nossa comunidade!",
        "menu_about": "Sobre...",
        "tooltip_undo": "Desfazer (Ctrl+Z)",
        "tooltip_redo": "Refazer (Ctrl+Y)",
        "tooltip_news": "Atualizações e Registro de Alterações",
        "btn_news": "Notícias",

        // --- RIBBON TABS ---
        "tab_insert": "Inserir",
        "tab_world_settings": "Configurações do Mundo",
        "tab_create": "Criar",
        "tab_view": "Visualizar",
        "btn_export": "Exportar",
        "btn_world_info": "Info do Mundo",

        // --- INSERT TAB ---
        "tooltip_paste": "Colar (Ctrl+V)",
        "btn_paste": "Colar",
        "tooltip_cut": "Recortar (Ctrl+X)",
        "tooltip_copy": "Copiar (Ctrl+C)",
        "lbl_clipboard": "Área de Transferência",
        "lbl_size": "Tamanho",
        "lbl_rounded": "Arredondado",
        "tooltip_spray": "Alternar Modo Spray",
        "btn_spray": "Spray",
        "lbl_brush_settings": "Configurações do Pincel",
        "tooltip_inventory": "Abrir Inventário (E)",
        "lbl_inventory": "Inventário (E)",
        "tooltip_save_struct": "Selecione uma área primeiro",
        "btn_save_structure_multiline": "Salvar<br>Estrutura",
        "lbl_empty": "Vazio",
        "tooltip_structures": "Abrir Biblioteca / Ver Tudo",
        "lbl_structures_tab": "Estruturas (R)",
        "tooltip_mobs": "Abrir Navegador de Mobs",
        "lbl_mobs_tab": "Mobs (M)",

        // --- WORLD SETTINGS TAB ---
        "lbl_gamemode": "Modo de Jogo:",
        "gm_survival": "Sobrevivência",
        "gm_creative": "Criativo",
        "gm_adventure": "Aventura",
        "gm_spectator": "Espectador",
        "lbl_difficulty": "Dificuldade:",
        "diff_peaceful": "Pacífico",
        "diff_easy": "Fácil",
        "diff_normal": "Normal",
        "diff_hard": "Difícil",
        "lbl_cheats": "Cheats",
        "lbl_hardcore": "Hardcore",
        "lbl_day": "Dia:",
        "tooltip_days_passed": "Dias passados (Somente Leitura)",
        "lbl_time": "Hora:",
        "lbl_live_time": "Tempo Real",
        "lbl_weather": "Clima:",
        "weather_clear": "Limpo",
        "weather_rain": "Chuva",
        "weather_thunder": "Tempestade",
        "lbl_world_settings": "Configurações do Mundo",
        "btn_manage_achievements": "Gerenciar<br>Conquistas",
        "lbl_achievements": "Conquistas",
        "lbl_keep_inv": "Manter<br>Inv.",
        "lbl_daylight_cycle": "Ciclo<br>de Dia",
        "lbl_mob_griefing": "Dano de<br>Mobs",
        "lbl_mob_loot": "Loot de<br>Mobs",
        "lbl_fire_tick": "Prop.<br>Fogo",
        "lbl_gamerules": "Regras do Jogo",
        "lbl_health": "Vida",
        "lbl_hunger": "Fome",
        "lbl_xp": "XP",
        "lbl_player": "Jogador",

        // --- CREATE TAB ---
        "btn_create_chest": "Criar<br>Baú de Loot",
        "lbl_chests": "Baús",
        "btn_create_item": "Criar<br>Item",
        "lbl_custom_items": "Itens Personalizados",

        // --- VIEW TAB ---
        "lbl_show_grid": "Mostrar Grade",
        "lbl_grid": "Grade",
        "btn_change_dim": "Mudar<br>Dimensão",
        "lbl_dimensions": "Dimensões",
        "lbl_weather_anim": "Animação<br>de Clima",

        // --- TOOLBAR ---
        "tooltip_tool_move": "Ferramenta Mover",
        "tooltip_tool_pencil": "Lápis",
        "tooltip_tool_eraser": "Borracha",
        "tooltip_tool_bucket": "Balde",
        "tooltip_tool_select": "Selecionar",
        "tooltip_tool_magic": "Varinha Mágica",
        "tooltip_tool_lasso": "Laço",
        "tooltip_tool_eyedropper": "Conta-gotas",
        "tooltip_screenshot": "Captura de Tela",

        // --- SIDEBAR WORLD INFO ---
        "side_info_title": "Info do Mundo",
        "side_info_name": "Nome do Mundo:",
        "side_info_author": "Criador:",
        "side_info_version": "Versão:",
        "side_info_seed": "Semente:",
        "side_info_cheats": "Cheats Ativados:",
        "side_info_dragon": "Enderdragon Derrotado:",
        "side_info_size": "Tamanho do Arquivo: ",

        // --- MODAL: SETTINGS ---
        "config_title": "Configuração",
        "config_language": "Idioma",
        "config_theme": "Tema",
        "config_autosave": "Intervalo de Autosalvamento",
        "config_off": "Desligado (Desativado)",
        "config_1m": "A cada 1 minuto",
        "config_5m": "A cada 5 minutos",
        "config_10m": "A cada 10 minutos",
        "config_volume": "Volume Principal",

        // --- MODAL: INVENTORY ---
        "modal_inventory": "Inventário",
        "pl_search": "Pesquisar...",
        "chest_content_title": "Conteúdo do Baú de Loot",
        "pl_chest_name": "Nome do Baú...",
        "btn_save_chest": "Salvar Baú",
        "item_creator_title": "Criador de Itens Personalizados",
        "btn_save_item": "💾 Salvar Item",
        "msg_select_first": "Selecione um item",
        "lbl_enchantments": "Encantamentos",

        // --- MODAL: STRUCTURES ---
        "struct_browser_title": "Navegador de Estruturas",
        "tab_saved": "Salvos",
        "tab_vanilla": "Vanilla",
        "tab_community": "Comunidade",
        "tooltip_import_json": "Importar JSON",
        "btn_import_mini": "📥 Importar",
        "tooltip_export_json": "Exportar JSON",
        "btn_export_mini": "💾 Exportar",
        "tooltip_delete_all": "Excluir Todos os Salvos",
        "btn_reset_mini": "⚠️ Resetar",
        "sub_all": "Todos",
        "sub_structures": "Estruturas",
        "sub_chests": "Baús",
        "sub_houses": "Casas",
        "sub_pixel_art": "Pixel Art",
        "sub_other": "Outros",
        "btn_gen_chest": "Gerar Baú",
        "lbl_author": "Criador:",
        "lbl_category": "Categoria:",
        "btn_load_struct": "Carregar Estrutura",
        "tooltip_edit_info": "Editar Info",
        "btn_edit": "Editar",
        "tooltip_delete": "Excluir",
        "btn_delete": "Excluir",

        // --- MODAL: MOBS ---
        "mob_browser_title": "Navegador de Mobs",
        "tab_animals": "Animais",
        "tab_overworld": "Superfície",
        "tab_nether": "Nether",
        "tab_end": "Fim",
        "lbl_health_hp": "Vida: 20 HP",
        "btn_spawn_mob": "Gerar Mob",

        // --- MODAL: SAVE STRUCTURE ---
        "modal_save_struct_title": "Salvar Nova Estrutura",
        "lbl_title": "Título",
        "pl_text": "Texto",
        "pl_username": "Nome de Usuário",
        "lbl_category_hidden": "Categoria",
        "lbl_tag": "Tag",
        "sub_structure": "Estrutura",
        "sub_house": "Casa",
        "sub_vehicle": "Veículo",
        "btn_cancel": "Cancelar",
        "btn_save": "Salvar",

        // --- MODAL: ACHIEVEMENTS ---
        "achiev_title": "Conquistas",
        "btn_unlock_all": "Desbloquear Todas",
        "btn_reset_all": "Resetar Todas",
        "ach_breed": "Procrie dois animais",
        "ach_brew": "Faça uma poção",
        "ach_crafting": "Crie uma bancada de trabalho",
        "ach_stone_pick": "Crie uma picareta de pedra",
        "ach_wood_pick": "Crie uma picareta de madeira",
        "ach_iron_pick": "Crie uma picareta de ferro",
        "ach_flaming_chicken": "Derrote uma galinha em chamas",
        "ach_eat": "Coma alguma comida",
        "ach_enchant": "Encante um item",
        "ach_bow": "Dispare um arco",
        "ach_fish": "Pesque um peixe",
        "ach_farm": "Cultive uma plantação",
        "ach_tree": "Cresça uma árvore",
        "ach_cake": "Faça um bolo",
        "ach_furnace": "Faça uma fornalha",
        "ach_iron_ingot": "Faça um lingote de ferro",
        "ach_portal_stone": "Faça uma pedra de portal",
        "ach_torches": "Faça algumas tochas",
        "ach_mine_wood": "Minere um bloco de madeira",
        "ach_mine_diamond": "Minere diamantes",
        "ach_mine_gold": "Minere ouro",
        "ach_mine_obsidian": "Minere obsidiana",
        "ach_door_wiring": "Abra uma porta com fiação",
        "ach_open_inv": "Abra o inventário",
        "ach_place_block": "Coloque um bloco",
        "ach_slay_blaze": "Mate um blaze",
        "ach_slay_cow": "Mate uma vaca",
        "ach_slay_creeper": "Mate um creeper",
        "ach_slay_ghast": "Mate um ghast com sua bola de fogo",
        "ach_slay_magma": "Mate um cubo de magma",
        "ach_slay_nethereye": "Mate um nethereye",
        "ach_slay_pig": "Mate um porco",
        "ach_slay_sheep": "Mate uma ovelha",
        "ach_slay_skeleton": "Mate um esqueleto",
        "ach_slay_slime": "Mate um slime",
        "ach_slay_spider": "Mate uma aranha",
        "ach_slay_zombie": "Mate um zumbi",
        "ach_slay_zpigman": "Mate um homem-porco zumbi",
        "ach_slay_enderman": "Mate um enderman",
        "ach_slay_dragon": "Mate o dragão do fim",
        "ach_tame_dog": "Dome um cachorro",
        "ach_tp_pearl": "Teletransporte-se com uma pérola do fim",
        "ach_travel_nether": "Viaje para o nether",
        "ach_unlock_end": "Desbloqueie o portal do fim",
        "ach_use_bed": "Use uma cama",
        "ach_use_anvil": "Use uma bigorna",

        // --- MODAL: DIMENSIONS ---
        "dim_title": "Selecionar Dimensão",

        // --- MODAL: EDIT INFO ---
        "edit_info_title": "Editar Info da Estrutura",
        "btn_update": "Atualizar",

        // --- MODAL: CONFIRM ---
        "confirm_title": "Confirmar Ação",
        "confirm_msg": "Tem certeza?",
        "btn_yes": "Sim",
        "btn_no": "Não",

        // --- MODAL: NEWS ---
        "news_title": "📰 Atualizações",
        "btn_back": "Voltar",

        // --- MODAL: LIGHTBOX ---
        "tooltip_close": "Fechar",

        // --- LOADING ---
        "loading_world": "Carregando Mundo...",

        // --- CHAT ---
        "pl_chat": "Pressione Enter para falar...",

        // --- STATUS BAR ---
        "tooltip_fps": "Quadros Por Segundo",
        "status_ready": "Pronto",
        "tooltip_zoom_out": "Menos Zoom",
        "tooltip_zoom_in": "Mais Zoom",
        "tooltip_zoom_reset": "Clique para Restaurar",
        "tooltip_fullscreen": "Tela Cheia",

        // --- PROFILE ---
        "profile_title": "Meu Perfil",
        "lbl_username": "Nome de Usuário:",

        // --- ABOUT ---
        "about_desc": "Uma ferramenta web para Mine Blocks para projetar, editar e compartilhar seus mundos favoritos diretamente do seu navegador.",
        "about_last_update": "Última Atualização:",

        // --- UI HANDLER JS ---
        "cat_all": "Todos os Itens",
        "cat_custom": "Personalizados",
        "cat_blocks": "Blocos",
        "cat_decoration": "Decoração",
        "cat_transportation": "Transporte",
        "cat_tools": "Ferramentas",
        "cat_food": "Comida e Plantações",
        "cat_armor": "Armadura",
        "cat_potions": "Poções",
        "cat_enchantedbooks": "Livros Encantados",

        "tooltip_open_inv": "Clique para abrir o Inventário",
        "lbl_creative_inv": "Inventário Criativo",
        "pl_search_item": "Procurar item... (ex: Diamante)",
        "lbl_none": "Nenhum",
        "tooltip_spawn": "Gerar",
        "msg_no_bases": "Nenhuma base encontrada.",
        "msg_no_custom_mobs": "Ainda não há mobs personalizados.<br>Vá em Criar > Mob Personalizado!",
        "lbl_health_hp_prefix": "Vida: ",
        "msg_system": "Sistema",
        "msg_spawn_custom": "⚡ Você gerou sua criação: ",
        "msg_spawn_saved": "⚡ Criado e salvo: ",
        "err_template_not_found": "Erro: Modelo não encontrado para",
        "lbl_mutant": "Mutante",
        "lbl_enchanted_book": "Livro Encantado",
        "lbl_potion_effect": "Efeito da Poção",
        "lbl_custom_chest": "Baú Personalizado",
        "msg_tp": "ZUP! Teletransportado para",
        
        // --- FILE MENU (BACKSTAGE) ---
        "menu_back": "Voltar",
        "menu_my_worlds": "Meus Mundos",
        "menu_templates": "Modelos",
        "menu_multiplayer": "Multijogador",
        "menu_load_world": "Carregar Mundo",
        "menu_export": "Exportar",
        "tooltip_change_pfp": "Clique para mudar a foto",
        "mp_public_servers": "Servidores Públicos",
        "mp_searching_worlds": "Procurando por mundos...",
        "mp_join_or_create": "Entrar por ID ou Crie o seu:",
        "mp_create_server": "Criar Servidor",
        "mp_paste_id": "Cole o ID aqui...",
        "mp_connect": "Conectar",
        "mp_players_limit": "Limite de Jogadores:",
        "mp_access": "Acesso: ",
        "mp_public": "Público",
        "mp_next": "Próximo",
        "mp_cancel": "Cancelar",
        "mp_select_map": "Selecionar Mapa:",
        "mp_generate_start": "Gerar ID e Iniciar",
        "mp_room_id": "ID da sua Sala (Compartilhe):",
        "mp_click_copy": "Clique para copiar!",
        "mp_id_placeholder": "O ID aparecerá aqui...",
        "mp_copied": "Copiado para a área de transferência!",
        "mp_close_server": "Fechar Servidor e Voltar",
        "mp_status_not_connected": "Status: Não Conectado",
        "mp_online": "En Línea",
        "mp_loading_players": "Carregando jogadores...",
        "mp_chats": "Chats",
        "mp_select_chat": "Selecione um chat para iniciar",
        "mp_name_placeholder": "Nome",
        "mp_send_message": "Enviar uma mensagem...",
        "mp_inbox": "Caixa de Entrada",
        "fs_no_saved_worlds": "Nenhum mundo salvo ainda",
        "fs_start_template": "Comece a partir de um Modelo",
        "tooltip_delete_world": "Excluir Mundo",
		// --- ADDON: PIXEL ART ---
        "pixelart_title": "Construtor Automático de Pixel Art",
        "pixelart_desc": "Envie uma imagem e o editor a construirá no mundo usando blocos de lã e argila.",
        "pixelart_max_width": "Tamanho Máximo (Largura em Blocos):",
        "pixelart_warning": "Imagens muito grandes podem causar lag.",
        "btn_pixelart_upload": "Carregar Imagem e Construir",
		"config_tab_theme": "🎨 Tema",
        "config_tab_autosave": "💾 Auto-salvamento",
        "config_tab_language": "🌍 Idioma",
        "config_tab_startup": "🚀 Início",
        "config_tab_volume": "🔊 Volume",
        "config_tab_controls": "⌨️ Controles",
        "config_theme_select": "Selecione seu tema preferido:",
        "theme_dark": "⚫ Escuro (Padrão)",
        "theme_white": "⚪ Branco",
        "theme_pastel": "🌸 Pastel",
        "theme_pastel2": "🌸 Pastel 2 (Cool)",
        "theme_darkblue": "🔵 Azul Escuro",
        "theme_winxp": "🪟 Windows XP",
        "config_autosave_label": "Intervalo de auto-salvamento:",
        "config_language_label": "Selecionar idioma:",
        "config_startup_label": "Escolha o que ver ao abrir o aplicativo:",
        "config_volume_desc": "Ajustar nível geral de áudio",
        "btn_reset_keybinds": "Redefinir",
        "controls_instructions": "Clique em um botão e pressione uma nova tecla para alterar o atalho.",
		"addons_tab_btn": "➕ Addons",
        "addon_spawnskin_title": "Visualização de Spawnskins",
        "addon_spawnskin_desc": "Envie planilhas de skins para ver a visualização de spawnskin no mundo.",
        "addon_pixelart_title": "[Demo] Construtor Automático de Pixel Art",
        "addon_pixelart_desc": "Converta qualquer imagem em uma grande pixel art.",
        "btn_open_addon": "Abrir",
        "btn_more_addons": "➕ Mais Add-ins",
		"spawnskin_modal_title": "Gerador de Visualização de Spawnskins",
        "spawnskin_modal_desc": "Para ver as spawnskins no editor, você precisa usar esta ferramenta.",
        "spawnskin_step1": "1. Abra o 'Gerador de Visualização de Spawnskins'",
        "btn_open_generator": "Abrir Ferramenta",
        "spawnskin_step2": "2. Carregue a lista de skins aqui:",
        "btn_import_skins": "Importar skins",
        "lbl_imported_skins": "Spawnskins Importadas",
		"news_title": "📰 Novidades",
    "btn_back": "Voltar",
    "news_v23_title": "v2.3 - Atualização Multiplayer",
    "news_v23_date": "25 de Abril de 2026",
    "news_v23_desc": "Crie um mapa com amigos, converse com eles e muito mais!",
    "news_v22_title": "v2.2 - Atualização de Baús",
    "news_v22_date": "23 de Março de 2026",
    "news_v22_desc": "Grande atualização incluindo novas estruturas, varinha mágica, itens personalizados, sistema de abas e muito mais!",
    "news_v21_title": "v2.1 - Atualização de Estruturas",
    "news_v21_date": "23 de Fevereiro de 2026",
    "news_v21_desc": "Biblioteca de estruturas, ferramentas aprimoradas, nova interface e correção de bugs.",
    "news_v20_title": "v2.0",
    "news_v20_date": "16 de Janeiro de 2026",
    "news_v20_desc": "Nova interface, Copiar-Colar, Zoom e muito mais!",
    }
};

// Leemos el idioma guardado en el navegador (por defecto inglés)
let currentLang = localStorage.getItem('mbw_lang') || 'en';

// Función para JS (Alertas, tooltips, etc.)
window.t = function(key) {
    return i18n[currentLang][key] || key; 
};

// Función que traduce el HTML en tiempo real
window.setLanguage = function(langCode) {
    if (!i18n[langCode]) return;
    
    currentLang = langCode;
    localStorage.setItem('mbw_lang', currentLang); // Guardar preferencia

    // Actualiza el selector del menú Configuration
    const selectEl = document.getElementById('lang-select');
    if (selectEl) selectEl.value = currentLang;

    // Escanear y traducir todos los textos del HTML
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (i18n[currentLang][key]) {
            el.innerHTML = i18n[currentLang][key]; // Reemplaza el texto (soporta <br>)
        }
    });

    // Escanear y traducir los "placeholder" de los inputs
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (i18n[currentLang][key]) {
            el.placeholder = i18n[currentLang][key];
        }
    });

    // Escanear y traducir los títulos/tooltips (title="")
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const key = el.getAttribute('data-i18n-title');
        if (i18n[currentLang][key]) {
            el.title = i18n[currentLang][key];
        }
    });
};

// Ejecutar la traducción automáticamente apenas carga la página
window.addEventListener('DOMContentLoaded', () => {
    setLanguage(currentLang);
});